name: Deploy to Odoo Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "üöÄ Starting Deployment..."

            # 1. Go to the folder
            cd /root/odoo-projects/ELB/addons/entrpryz_construction_boq

            # ‚¨áÔ∏è NEW LINE: Tell Git to trust this folder!
            git config --global --add safe.directory /root/odoo-projects/ELB/addons/entrpryz_construction_boq

            # Stash the changes before pulling the code
            git stash

            # 2. Pull the latest code
            git pull origin main

            # 3. Fix Permissions
            echo "üîß Fixing permissions..."
            chown -R 101:101 /root/odoo-projects/ELB/addons/entrpryz_construction_boq
            chmod -R 755 /root/odoo-projects/ELB/addons/entrpryz_construction_boq

            # 4. Restart the Container
            echo "üîÑ Restarting Container..."
            docker restart elb-entrpryz-one-p3390e-web-1

            echo "‚úÖ Deployment Finished!"
